# GUI Applications
cask "spotify"
cask "notion"
cask "firefox"
cask "slack"
cask "visual-studio-code"
cask "microsoft-office"
cask "rectangle"
cask "1password"
cask "cursor"
cask "zoom"
cask "inkscape"
cask "kiwix"
cask "teamviewer"
cask "discord"

# CLI Tools
brew "wget"
brew "tree"
brew "imagemagick"
